### ISSUE TITLE
Plan for face-centered fields

### ISSUE THREAD

**Issue by Yurlungur** [parthenon-hpc-lab/parthenon#736]
From Hackathon:
- Cell vars generalized to become differently shaped fields
- Generalize "WithFluxes" to be more verbose about what kind of fluxes
- "EMF correction" implemented as "line integral correction"
- Keep in mind concern about order of operations

TODOS:
- [x] Flux correction in one (Luke)
- [x] Remove all the old face-centered stuff leftover from athena++ (Forrest) #738 
- [x] Rename CC and Cell to Var (Josh) #867 
- [x] Implement newly shaped vars. (Josh) #868 
- [x] Add metadata. (Josh) #868 
- [x] Pull newly shaped vars through packs. Remove `GetDim` from packs (Luke, Deferred to pack discussion) #868 
- [x] Update/Fix single-level comms and fluxes (Philipp) #872 
- [x] Physical boundary conditions -> `MeshData` so prolongation/restriction can be done in-one
- [x] Pull Prolongation/Restriction hooks to userspace (Jonah) #769 
- [x] Pull prolongation/restriction through new vars (Pull from AthenaK) #872 
- [ ] Include face-centered fields, etc. in output
- [ ] Post-implementation cleanup
- [ ] Documentation

**Comment by Yurlungur** [comment]
Additional note: AMR load balance is missing some logic for tensor-valued quantities to communicate tensor values accross mesh boundaries. We need to repeat what @brryan did for buffer packing.

**Comment by lroberts36** [comment]
One of the TODOs is to "Add metadata", does anyone know what this refers to? It looks like metadata already exists for faces, edges, and nodes. Is is just referring to update metadata to change the shapes of variables based on their topological type?

**Comment by pgrete** [comment]
Good question. Your first guess would have also been mine.

**Comment by Yurlungur** [comment]
I'm not sure either. Let's just check it off lol.
